"""Dependencies shared by all routers, as ready-to-use ``Annotated`` aliases.

A route declares what it needs by type and FastAPI supplies it per request:

    @router.post("/jobs", status_code=201)
    async def create_job(
        body: JobCreateRequest,
        session: SessionDep,          # authenticated caller (401 otherwise)
        repos: ReposDep,              # repositories for every collection
        provider: ProviderDep,        # the configured AI provider
        quotas: QuotasDep,            # per-session quota + global AI call cap
        sessions: SessionServiceDep,  # guard_after_write
        settings: SettingsDep,
    ) -> Job: ...
"""

import re
from typing import Annotated

from fastapi import Depends, Header

from app.config import Settings, get_settings
from app.db import Database, get_db
from app.errors import IdempotencyKeyRequired
from app.providers.base import AIProvider
from app.providers.factory import get_provider
from app.ratelimit import QuotaService
from app.repositories import Repositories
from app.schemas.generations import IDEMPOTENCY_KEY_MAX_LENGTH, IDEMPOTENCY_KEY_MIN_LENGTH
from app.security import SessionContext, require_session
from app.services.sessions import SessionService

SettingsDep = Annotated[Settings, Depends(get_settings)]
DbDep = Annotated[Database, Depends(get_db)]
SessionDep = Annotated[SessionContext, Depends(require_session)]
ProviderDep = Annotated[AIProvider, Depends(get_provider)]


def get_repos(db: DbDep) -> Repositories:
    return Repositories(db)


ReposDep = Annotated[Repositories, Depends(get_repos)]


def get_quotas(repos: ReposDep, settings: SettingsDep) -> QuotaService:
    return QuotaService(repos.counters, repos.sessions, settings)


QuotasDep = Annotated[QuotaService, Depends(get_quotas)]


def get_session_service(
    repos: ReposDep, settings: SettingsDep, provider: ProviderDep
) -> SessionService:
    return SessionService(repos, settings, provider.mode)


SessionServiceDep = Annotated[SessionService, Depends(get_session_service)]

# Visible ASCII without spaces, e.g. a UUID generated by the browser.
_IDEMPOTENCY_KEY_PATTERN = re.compile(
    rf"[\x21-\x7e]{{{IDEMPOTENCY_KEY_MIN_LENGTH},{IDEMPOTENCY_KEY_MAX_LENGTH}}}"
)


def require_idempotency_key(
    idempotency_key: Annotated[str | None, Header()] = None,
) -> str:
    """The ``Idempotency-Key`` header, or 400 idempotency_key_required when it
    is missing or not 8-128 visible ASCII characters."""
    if idempotency_key is None or not _IDEMPOTENCY_KEY_PATTERN.fullmatch(idempotency_key):
        raise IdempotencyKeyRequired()
    return idempotency_key


IdempotencyKeyDep = Annotated[str, Depends(require_idempotency_key)]
